// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1dM7vCRSxOys8uRL932tFsYajpjVzyBM',
    appId: '1:462905650026:web:5c2bd808a314bace609313',
    messagingSenderId: '462905650026',
    projectId: 'fruitshub-9de3c',
    authDomain: 'fruitshub-9de3c.firebaseapp.com',
    storageBucket: 'fruitshub-9de3c.firebasestorage.app',
    measurementId: 'G-G563740Y28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb-SCbmVDSDh-TUe7HcNJFs-ASPY_0Cz0',
    appId: '1:462905650026:android:15f056ff9e8ab1c2609313',
    messagingSenderId: '462905650026',
    projectId: 'fruitshub-9de3c',
    storageBucket: 'fruitshub-9de3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx-GVtn_RoapnE3QliiNWl3YFJMf5jNlE',
    appId: '1:462905650026:ios:82d661262fca0404609313',
    messagingSenderId: '462905650026',
    projectId: 'fruitshub-9de3c',
    storageBucket: 'fruitshub-9de3c.firebasestorage.app',
    androidClientId: '462905650026-68gspbjf72gr8qh6bo8jjsc3pjd42t23.apps.googleusercontent.com',
    iosClientId: '462905650026-0es4bhi0v5tk4hcul0elljtsutujfma5.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashBoard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx-GVtn_RoapnE3QliiNWl3YFJMf5jNlE',
    appId: '1:462905650026:ios:82d661262fca0404609313',
    messagingSenderId: '462905650026',
    projectId: 'fruitshub-9de3c',
    storageBucket: 'fruitshub-9de3c.firebasestorage.app',
    androidClientId: '462905650026-68gspbjf72gr8qh6bo8jjsc3pjd42t23.apps.googleusercontent.com',
    iosClientId: '462905650026-0es4bhi0v5tk4hcul0elljtsutujfma5.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashBoard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1dM7vCRSxOys8uRL932tFsYajpjVzyBM',
    appId: '1:462905650026:web:7ffbb57d5ae7992e609313',
    messagingSenderId: '462905650026',
    projectId: 'fruitshub-9de3c',
    authDomain: 'fruitshub-9de3c.firebaseapp.com',
    storageBucket: 'fruitshub-9de3c.firebasestorage.app',
    measurementId: 'G-FKJGPPDPHB',
  );
}
